apiVersion: v1
kind: Service
metadata:
  name: beehive-upload-server
spec:
  selector:
    app: beehive-upload-server
  ports:
    - protocol: TCP
      port: 49192
      targetPort: 22
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: beehive-upload-server
spec:
  serviceName: beehive-upload-server
  selector:
    matchLabels:
      app: beehive-upload-server
  template:
    metadata:
      labels:
        app: beehive-upload-server
    spec:
      containers:
      - image: waggle/beehive-upload-server
        name: beehive-upload-server
        env:
        - name: SSH_CA_PUBKEY
          value: "/etc/ca/ca.pub"
        - name: SSH_HOST_KEY
          value: "/etc/waggle/ssh-host-key"
        - name: SSH_HOST_CERT
          value: "/etc/waggle/ssh-host-key-cert.pub"
        ports:
        - name: ssh
          containerPort: 22
        volumeMounts:
        - name: ssh-ca-key
          mountPath: /etc/ca
          readOnly: true
        - name: ssh-host-key
          mountPath: /etc/waggle
          readOnly: true
        - name: home-dirs
          mountPath: /home
        livenessProbe:
          tcpSocket:
            port: ssh
          initialDelaySeconds: 5
          periodSeconds: 60
      volumes:
      - name: ssh-ca-key
        configMap:
          name: beehive-ssh-ca
      - name: ssh-host-key
        secret:
          secretName: beehive-upload-server-ssh-host-key
          defaultMode: 0600
      - name: home-dirs
        hostPath:
          # TODO(sean) make this part of config
          path: /root/upload-server-home-dirs
          type: DirectoryOrCreate
