apiVersion: apps/v1
kind: Deployment
metadata:
  name: beehive-influxdb-loader
spec:
  selector:
    matchLabels:
      app: beehive-influxdb-loader
  template:
    metadata:
      labels:
        app: beehive-influxdb-loader
    spec:
      containers:
      - name: beehive-influxdb-loader
        image: waggle/beehive-influxdb-loader
        env:
          - name: RABBITMQ_HOST
            value: "beehive-rabbitmq"
          - name: RABBITMQ_PORT
            value: "5671"
          - name: RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: beehive-influxdb-loader-auth
                key: username
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: beehive-influxdb-loader-auth
                key: password
          - name: RABBITMQ_CACERTFILE
            value: "/etc/tls/cacert.pem"

          - name: INFLUXDB_URL
            value: "http://beehive-influxdb:8086"
          - name: INFLUXDB_BUCKET
            value: "waggle"
          - name: INFLUXDB_ORG
            value: "waggle"
          - name: INFLUXDB_TOKEN
            valueFrom:
              secretKeyRef:
                name: beehive-influxdb-loader-secret
                key: token
        volumeMounts:
          - name: ca-certificate
            mountPath: "/etc/tls"
            readOnly: true
      volumes:
        - name: ca-certificate
          configMap:
            name: beehive-ca-certificate
